name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to AWS ECR
    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build Docker images and push to ECR
    - name: Build and Push Docker images
      run: |
        docker build -t ${{ secrets.255945442255.dkr.ecr.us-east-1.amazonaws.com/service-1-repo }} ./file-upload-service
        docker build -t ${{ secrets.255945442255.dkr.ecr.us-east-1.amazonaws.com/service-2-repo }} ./message-queue-service

        docker push ${{ secrets.255945442255.dkr.ecr.us-east-1.amazonaws.com/service-1-repo }}
        docker push ${{ secrets.255945442255.dkr.ecr.us-east-1.amazonaws.com/service-2-repo }}

    # Step 5: Deploy to ECS
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ecs-app-cluster \
          --service file-upload-service \
          --force-new-deployment

        aws ecs update-service --cluster ecs-app-cluster \
          --service message-queue-service \
          --force-new-deployment
